from fastapi import FastAPI, Request
from api.functions import get_month_data
import traceback
import sys

app = FastAPI()

# ===== –≠–Ω–¥–ø–æ–∏–Ω—Ç —Å—Ç–∞—Ç–∏—Å—Ç–∏–∫–∏ =====
@app.get("/api/data")
async def get_data(request: Request, month: int, year: int):
    try:
        print(f"üìÖ –ó–∞–ø—Ä–æ—Å –¥–∞–Ω–Ω—ã—Ö –∑–∞ {month}/{year}")
        output = await get_month_data(month, year)
        print("‚úÖ –£—Å–ø–µ—à–Ω–æ –ø–æ–ª—É—á–∏–ª–∏ –¥–∞–Ω–Ω—ã–µ")
        return output
    except Exception as e:
        err_type, err_value, err_tb = sys.exc_info()
        err = "".join(traceback.format_exception(err_type, err_value, err_tb))
        print("‚ùå –ü–æ–ª–Ω–∞—è –æ—à–∏–±–∫–∞ –≤ get_data:\n", err)
        return {"error": err}
